"""SAPN November 2022 workflow settings."""

from datetime import time

VALID_VOLTAGE_MIN = 80.0
VALID_VOLTAGE_MAX = 300.0
VOLTAGE_ROLLING_WINDOW = "10m"
DEDUPLICATION_ABSOLUTE_TOLERANCE_KW = 0.2
DEDUPLICATION_RELATIVE_TOLERANCE = 0.05
LOCAL_TIMEZONE = "Australia/Adelaide"

EVENT_YEAR = 2022
EVENT_MONTH = 11
EVENT_DAYS = (13, 14, 15, 16, 17, 19)
DAY_EXTRACTION_START = time(5, 50)
DAY_ANALYSIS_START = time(6, 0)
DAY_END = time(18, 0)
DAY_COVERAGE_THRESHOLD = 0.08
DAY_WINDOW_SECONDS = 12 * 60 * 60

REQUIRED_SITE_METADATA_ROWS = 1
MAX_PV_SITE_NET_CIRCUITS = 3
PHASE_B_METHODS = ("tier_based",)
PRIMARY_PHASE_B_METHOD = "tier_based"
GENERATE_SITE_PLOTS = True
PLOT_NO_RESPONSIBLE_TIMESTAMP_DAYS = False
SAVE_SITE_LEVEL_VARIOUS_VOLTAGES = True
