"""Solar Analytics workflow settings."""

from datetime import time

VALID_VOLTAGE_MIN = 80.0
VALID_VOLTAGE_MAX = 300.0
VOLTAGE_ROLLING_WINDOW = "10m"
DEDUPLICATION_ABSOLUTE_TOLERANCE_KW = 0.2
DEDUPLICATION_RELATIVE_TOLERANCE = 0.05
LOCAL_TIMEZONE = "Australia/Adelaide"

DAY_EXTRACTION_START = time(5, 50)
DAY_ANALYSIS_START = time(6, 0)
DAY_END = time(18, 0)
DAY_COVERAGE_THRESHOLD = 0.0
EXPECTED_TIMESTAMPS = 145

MAX_PV_SITE_NET_CIRCUITS = 3
PHASE_B_METHODS = ("tier_based",)
PRIMARY_PHASE_B_METHOD = "tier_based"

CONSIDER_LOWEST_THRESHOLD_AT_DISCONNECT = True

GENERATE_SITE_PLOTS = True
PLOT_NO_RESPONSIBLE_TIMESTAMP_DAYS = False
SAVE_SITE_LEVEL_VARIOUS_VOLTAGES = True
