name: Continuous Integration and Deployment

on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main
 workflow_dispatch: # manual trigger

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3
      # Install uv with cache
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      # Sync dependencies
      - name: Sync dependencies
        run: uv sync
      # Run tests without updating uv.lock
      - name: Run tests
        run: uv run --frozen pytest
      # Code coverage to codecov.io
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: tests/coverage.xml
          fail_ci_if_error: false
          verbose: true
